// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package com.linmour.system.grpc;

public final class grpc {
  private grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_LongList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_LongList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Result1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Result1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Result2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Result2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmess.proto\022\007service\032\031google/protobuf/a" +
      "ny.proto\"\032\n\010LongList\022\016\n\006values\030\001 \003(\003\"2\n\007" +
      "Result1\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\014\n\004da" +
      "ta\030\003 \001(\014\"$\n\007Result2\022\014\n\004code\030\001 \001(\005\022\013\n\003msg" +
      "\030\002 \001(\t2z\n\006System\0225\n\014getShopByIds\022\021.servi" +
      "ce.LongList\032\020.service.Result1\"\000\0229\n\020getMe" +
      "rchantByIds\022\021.service.LongList\032\020.service" +
      ".Result1\"\000B!\n\027com.linmour.system.grpcB\004g" +
      "rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_service_LongList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service_LongList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_LongList_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_service_Result1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service_Result1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Result1_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
    internal_static_service_Result2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service_Result2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Result2_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
