// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package com.linmour.websocket.grpc;

public final class grpc {
  private grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Result1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Result1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Result2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Result2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmess.proto\022\007service\"\026\n\006Object\022\014\n\004data\030" +
      "\001 \001(\t\"2\n\007Result1\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 " +
      "\001(\t\022\014\n\004data\030\003 \001(\014\"$\n\007Result2\022\014\n\004code\030\001 \001" +
      "(\005\022\013\n\003msg\030\002 \001(\t2;\n\005Order\0222\n\013createOrder\022" +
      "\017.service.Object\032\020.service.Result1\"\000B$\n\032" +
      "com.linmour.websocket.grpcB\004grpcP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_service_Object_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Object_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_service_Result1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service_Result1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Result1_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
    internal_static_service_Result2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service_Result2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Result2_descriptor,
        new java.lang.String[] { "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
