// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package com.linmour.product.grpc;

public final class GrpcService {
  private GrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_LongList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_LongList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Result1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Result1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_Result2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service_Result2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmess.proto\022\007service\032\031google/protobuf/a" +
      "ny.proto\"\026\n\006Object\022\014\n\004data\030\001 \001(\014\"\032\n\010Long" +
      "List\022\016\n\006values\030\001 \003(\003\"2\n\007Result1\022\014\n\004code\030" +
      "\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\"$\n\007Resu" +
      "lt2\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t2\201\001\n\007Produ" +
      "ct\022:\n\021getProductDetails\022\021.service.LongLi" +
      "st\032\020.service.Result1\"\000\022:\n\021reduceInventor" +
      "ies\022\021.service.LongList\032\020.service.Result2" +
      "\"\0002p\n\005Order\0223\n\014getOrderInfo\022\017.service.Ob" +
      "ject\032\020.service.Result1\"\000\0222\n\013createOrder\022" +
      "\017.service.Object\032\020.service.Result2\"\000B)\n\030" +
      "com.linmour.product.grpcB\013GrpcServiceP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_service_Object_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Object_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_service_LongList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service_LongList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_LongList_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_service_Result1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service_Result1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Result1_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
    internal_static_service_Result2_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service_Result2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service_Result2_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
