// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package com.linmour.product.grpc;

public interface LongListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.LongList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Long> getValuesList();
  /**
   * <code>repeated int64 values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated int64 values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  long getValues(int index);
}
