// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mess.proto

package com.linmour.order.grpc;

public interface Result1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.Result1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应编码
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * 响应提示信息
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * 响应提示信息
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <pre>
   * 响应内容，使用Any类型来传递任意类型的消息
   * </pre>
   *
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
